server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://node01:33306/fairy-cloud?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  data:
    elasticsearch:
      client:
        reactive:
          socket-timeout: 10000

elastic:
  host: node01
  port: 9200
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:mapper/*.xml
logging:
  level:
    root: INFO
    org.springframework.data.elasticsearch.core: DEBUG
    com.fairy.cloud.mbg.mapper: DEBUG
