version: '3'
networks:
  elastic-work:
    external: false
services:
  zipkin-server:
    image: openzipkin/zipkin
    container_name: sc-zipkin-server
    restart: always
    volumes:
      - /mydata/zipkin/logs:/var/logs
    networks:
      - elastic-work
    ports:
      - 9411:9411
    environment:
      - RABBIT_ADDRESSES=rabbitmq:5672
      - RABBIT_MQ_PORT=5672
      - RABBIT_PASSWORD=admin
      - RABBIT_USER=admin
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=http://elasticsearch:9200
    depends_on:
      - rabbitmq

  elasticsearch:
    image: elasticsearch:7.6.1
    container_name: elasticsearch
    restart: always
    environment:
      - cluster.name=elastic-nodes
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - node.name=node01
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /mydata/elasticsearch/config:/usr/share/elasticsearch/config
      - /mydata/elasticsearch/data:/usr/share/elasticsearch/data
      - /mydata/elasticsearch/plugins:/usr/share/elasticsearch/plugins
      - /mydata/elasticsearch/logs:/usr/share/elasticsearch/logs
    networks:
      - elastic-work
    ports:
      - 9200:9200
      - 9300:9300
  #  skywalking-oap:
  #    image: apache/skywalking-oap-server
  #    container_name: skywalking-oap
  #    networks:
  #      - elastic-work
  #    depends_on:
  #      - elasticsearch
  #    links:
  #      - elasticsearch
  #    restart: always
  #    ports:
  #      - 11800:11800
  #      - 12800:12800
  #    volumes:
  #      - ./devops/skywalking/config:/apache-skywalking-apm-bin/config:ro
  #
  #  skywalking-ui:
  #    image: wutang/skywalking-ui:6.1.0
  #    container_name: skywalking-ui
  #    networks:
  #      - sc-net
  #    depends_on:
  #      - skywalking-oap
  #    links:
  #      - skywalking-oap
  #    restart: always
  #    ports:
  #      - 8080:8080
  #    environment:
  #      collector.ribbon.listOfServers: skywalking-oap:12800


  kibana:
    image: kibana:7.6.1
    container_name: kibana
    restart: always
    environment:
      - ELASTICSEARCH_URL=http://node01:9200
    networks:
      - elastic-work
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    volumes:
      - /mydata/grafana/logs:/var/logs/grafana
    networks:
      - elastic-work
    ports:
      - 3000:3000

  rabbitmq:
    image: rabbitmq:3.6.5-management
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBIT_MQ_HOST=rabbitmq
      - RABBIT_MQ_PORT=5672
    volumes:
      - /mydata/rabbitmq/etc:/etc/rabbitmq
      - /mydata/rabbitmq/lib:/var/lib/rabbitmq
      - /mydata/rabbitmq/log:/var/log/rabbitmq
    networks:
      - elastic-work
    ports:
      - 5672:5672
      - 15672:15672