spring:
  redis:
    database: 0
    host: node01
    port: 63379
    password:
    timeout: 5000
    lettuce:
      pool:
        max-wait: -1
        max-idle: 10
        min-idle: 0
        max-active: 10
        command-time: 5000
  rabbitmq:
    host: node01
    port: 5672
    username: admin
    password: admin
    publisher-confirm-type: correlated
    virtual-host: /
    listener:
      simple:
        prefetch: 1
        concurrency: 5
        max-concurrency: 10
        acknowledge-mode: manual
        retry:
          max-attempts: 3
  zipkin:
    enabled: true
    sender:
      type: rabbit
  sleuth:
    enabled: true
    http:
      legacy:
        enabled: true
  security:
    oauth2:
      jwt:
        signingKey: 123123
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.alibaba.cloud.nacos.client: ERROR
  file:
    max-size: 1GB


rabbitmq:
  queue: gateway-event-queue
  exchange: gateway-event-exchange
  routingKey: gateway-event-route