spring:
  datasource:
    url: jdbc:mysql://node01:33306/fairy-cloud?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  redis:
    port: 63379
    password:
    host: node01
    database: 0
    jedis:
      pool:
        max-active: 10
        min-idle: 5
        max-idle: 10
        max-wait: -1
    timeout: 5000
mybatis-plus:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: auto
logging:
  level:
    root: INFO
    com.alibaba.cloud.nacos.client: ERROR
    com.fairy.cloud.mbg.mapper: DEBUG
  config: classpath:logback.xml

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

#zk配置
zk:
  curator:
    retryCount: 5 #重试次数
    elapsedTimeMs: 5000 #
    connectUrl: node01:22181 #zk地址
    sessionTimeOutMs: 60000 #会话超时时间
    connectionTimeOutMs: 5000 #连接超时时间