spring:
  redis:
    database: 0
    host: node01
    port: 63379
    password:
    timeout: 5000
    lettuce:
      pool:
        max-wait: -1
        max-idle: 10
        min-idle: 0
        max-active: 10
        command-time: 5000
  rabbitmq:
    host: node01
    port: 5672
    username: admin
    password: admin
    publisher-confirm-type: correlated
    virtual-host: /
  zipkin:
    enabled: true
    sender:
      type: rabbit
  sleuth:
    enabled: true
    http:
      legacy:
        enabled: true
  security:
    oauth2:
      jwt:
        signingKey: 123123
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.alibaba.cloud.nacos.client: ERROR
    com.fairy.cloud.mbg.mapper: DEBUG
    org.springframework.cloud.gateway.filter: trace
  file:
    max-size: 1GB

