spring:
  redis:
    database: 0
    password:
    host: node01
    port: 63379
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.alibaba.cloud.nacos.client: ERROR
    com.fairy.cloud.mbg.mapper: DEBUG
  config: classpath:logback.xml

cloud:
  gateway:
    shouldSkipUrls:
      - /auth/oauth/**
      - /sso/**
      - /home/**
      - /static/qrcode/**
