spring:
  rabbitmq:
    host: ${RABBIT_MQ_HOST:node01}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:admin}
    password: ${RABBIT_MQ_PASSWORD:admin}
    virtual-host: /
    publisher-confirm-type: correlated
    listener:
      direct:
        retry:
          enabled: true
  zipkin:
    locator:
      discovery:
        enabled: true
    enabled: true
    sender:
      type: rabbit
    base-url: http://node01:9411/  # zipkin服务器地址
    rabbitmq:
      addresses: node01:5672
      queue: zipkin
    service:
      name: ${spring.application.name}
      message-timeout: 5000
      discovery-client-enabled: false #关闭服务发现 否则springcloud会把zipkin的url当做服务名称
  sleuth:
    scheduled:
      enabled: true
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 采样频率
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    time-zone: GMT+8

logging:
  level:
    root: INFO
    com.alibaba.cloud.nacos.client: ERROR
    com.fairy.cloud.mbg.mapper: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
