spring:
  rabbitmq:
    host: ${RABBIT_MQ_HOST:node01}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:admin}
    password: ${RABBIT_MQ_PASSWORD:admin}
    virtual-host: /
    publisher-confirm-type: correlated
#    listener:
#      simple:
#        prefetch: 100
#        concurrency: 5
#        max-concurrency: 10
#        acknowledge-mode: manual
#        retry:
#          max-attempts:3
  redis:
    host: node01
    port: 63379
    password:
    database: 0
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://node01:33306/fairy-cloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: root
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: druid
        login-password: druid
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  ##日志链路追踪
  zipkin:
    enabled: true
    sender:
      type: rabbit
    base-url: http://node01:9411/
    rabbitmq:
      queue: zipkin
      addresses: node01:5672
  sleuth:
    scheduled:
      enabled: true
    web:
      skip-pattern: /health
    sampler:
      probability: 1.0
  mvc:
    throw-exception-if-no-handler-found: true
  #jwt的密钥
  security:
    oauth2:
      jwt:
        signingKey: 123123

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  hidePackages: com.faity.auth.authorication  # 隐藏包
  local:
    # 短時本地緩存，主要用于要求时效较高的配置
    default:
      type: caffeine #jvm linkedhashmap
      keyConvertor: fastjson
      expireAfterWriteInMillis: 60000
      expireAfterAccessInMillis: 40000
    otherArea:
      type: linkedhashmap
      limit: 100
      keyConvertor: none
      expireAfterWriteInMillis: 100000
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: node01
      port: 63379
    otherArea:
      type: redis
      keyConvertor: fastjson
      valueEncoder: kryo
      valueDecoder: kryo
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: ${spring.redis.host}
      port: ${spring.redis.port}
logging:
  level:
    com.springboot.cloud: debug
    org.springframework.web: debug
    org.springframework.security: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'

mybatis:
  configuration:
    map-underscore-to-camel-case: true